language: ruby
cache: bundler
sudo: required
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
 env:
   global:
     - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
before_install:
   - gem update --system
script:
   - bundle exec rubocop && xvfb-run bundle exec rspec spec
