language: ruby
cache: bundler
sudo: false
rvm:
 - 2.0.0-p598
 - 2.1.10
 - 2.2.10
 - 2.3.7
 - 2.4.4
 - 2.5.1
 - jruby-9.0.5.0
 - jruby-9.1.9.0
before_install:
  - gem update --system
script:
  - bundle exec rubocop && bundle exec rake
